update name used for legacy conf in financlial track dump
CruGlobal/staff-conf-onsite pull request #247
Opened 2022-08-07 12:36 UTC by jesusfreak3

2022-08-07 12:51 UTC, jesusfreak3 commented
Waiting for Andy to approve adjustment today

2022-08-07 16:14 UTC, knutsenm requested changes

2022-08-07 16:14 UTC, knutsenm commented on app/admin/family.rb
> +              when /Legacy.*/.match?(conference.name)
anchor that to beginning of the string?

2022-08-08 17:41 UTC, knutsenm commented on app/admin/family.rb
> +              when /Legacy.*/.match?(conference.name)
Or, if you merely must match "Legacy" anywhere, the pattern could be plain `/Legacy/`, although in this case regex is overkill and you could just use `.include?`

2022-08-09 14:20 UTC, knutsenm submitted a review, later dismissed

2022-08-09 14:21 UTC, knutsenm approved these changes

2022-08-09 14:25 UTC, merged