Okta intregration
CruGlobal/staff-conf-onsite pull request #253
Opened 2023-05-29 16:01 UTC by jesusfreak3

Replacing CAS with Okta

2023-06-21 20:26 UTC, knutsenm commented
If you `git rebase ruby_upgrade_3` (and change the base here), you'll get just the five new commits

2023-06-21 20:58 UTC, knutsenm commented
Have you been running tests locally? I'm not sure how to set them up.

2023-06-21 21:02 UTC, knutsenm commented
Are you able to get rid of all references to CAS, like in `.env` and `Gemfile` and `README.md` and `config/*` and `lib/cas_attributes.rb` (and various tests)?

2023-06-22 14:40 UTC, jesusfreak3 commented
> Are you able to get rid of all references to CAS, like in `.env` and `Gemfile` and `README.md` and `config/*` and `lib/cas_attributes.rb` (and various tests)?

Yup, its on my to do list, I am just waiting for Andy to finish going through the app to bring up any issues and then was going to go through them all at the same time.  But thanks for bringing it up!

2023-06-22 14:42 UTC, jesusfreak3 commented
> Have you been running tests locally? I'm not sure how to set them up.

Yup, I have them running locally on ubuntu server.    I had to install the selenium web driver and chrome and related libraries.

selenium web driver

sudo apt update 
sudo apt install -y unzip xvfb libxi6 libgconf-2-4 
sudo apt install default-jdk 

sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add 
sudo bash -c "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list" 
sudo apt -y update 
sudo apt -y install google-chrome-stable 

google-chrome --version 

wget https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip 

sudo mv chromedriver /usr/bin/chromedriver 
sudo chown root:root /usr/bin/chromedriver 
sudo chmod +x /usr/bin/chromedriver

2023-06-22 14:50 UTC, knutsenm commented
> > Have you been running tests locally? I'm not sure how to set them up.
> 
> Yup, I have them running locally on ubuntu server. I had to install the selenium web driver and chrome and related libraries.

That's fine. As long as it works for you, I can help you create an Action that will be similar to our existing lint/test Actions for other projects. We no longer use Travis.

2023-06-22 14:54 UTC, jesusfreak3 commented
> > > Have you been running tests locally? I'm not sure how to set them up.
> > 
> > 
> > Yup, I have them running locally on ubuntu server. I had to install the selenium web driver and chrome and related libraries.
> 
> That's fine. As long as it works for you, I can help you create an Action that will be similar to our existing lint/test Actions for other projects. We no longer use Travis.

Great, I run it manually locally just using the rake test, so shouldn't be to hard to get that moved to your new standard.

2023-07-31 21:49 UTC, knutsenm requested changes
Please rebase against `ruby_upgrade_3`

2023-07-31 21:49 UTC, knutsenm commented on app/models/concerns/active_model_resource_collection.rb
> +      ActiveRecord::ConnectionAdapters::Column.new(name.to_s, sql_type_metadata)
What happened to `default`?

2025-05-05 19:45 UTC, jesusfreak3 commented on app/models/concerns/active_model_resource_collection.rb
> +      ActiveRecord::ConnectionAdapters::Column.new(name.to_s, sql_type_metadata)
lol old message.. trying to clean up new PR by merging the old ones into master that were approved and work on staging.  So looking into this, default was never used in the code base when calling new column.  So we can remove it from the signature

2025-05-05 19:45 UTC, jesusfreak3 commented on app/models/concerns/active_model_resource_collection.rb
> +      ActiveRecord::ConnectionAdapters::Column.new(name.to_s, sql_type_metadata)
will add a note to do this in a new branch to keep things cleaner with all the PRS.

2025-05-05 20:11 UTC, knutsenm approved these changes
Approved, with the proviso that there is tidy-up work remaining:
> get rid of all references to CAS, like in .env and Gemfile and README.md and config/* and lib/cas_attributes.rb (and various tests)

2025-05-05 20:12 UTC, merged